### PR TITLE
Complete refactor of definitions.

### PR DESCRIPTION
**Pull request by yvoyer**
* Add more specific interface
* Add integration with PHPUnit
* Remove deprecated code
* Simplify Behat tests
* Remove PHPspec usage

### CODE REVIEW

**Comment by yvoyer** [comment]
@kevinarcher I would like your help on this one. I have issues with behat tests not passing. I think its caused by the AssertTrue class being included in the wrong order. Php seems to use the class constructed by the third scenario instead of using the code from the second one. The file AssertTrue.php contains the expected code for each scenario, but its possibly an opcode error.

**Step to reproduce**: 
* Install project: `composer.phar install`
* run `bin/behat`

**Actual Result**
The `User inputs a valid code` scenario fails, even if it returns true.

**Expected Result**
All the tests should be passing (you can test by running the command line for the fibonacci kata).

Execute `php phpkata.php start fibonacci`
Copy the following code in the `src/Fibonacci.php` file

    <?php
    class Fibonacci
    {
        public function getnumber($position)
        {
            switch ($position) {
                case 1: return 0;
                case 2: return 1;
                case 3: return 1;
                case 4: return 2;
                case 5: return 3;
                case 6: return 5;
                case 7: return 8;
                case 12: return 89;
                case 44: return 433494437;
            }
        }
    }

execute `php phpkata.php continue fibonacci`

**Comment by kevinarcher** [comment]
The first issue I see is that the "tests/features/bootstrap/tmp" folder does not exist. You should create it as part of the setup.

**Comment by yvoyer** [comment]
I know about the tmp folder. I forgot to add it in the repos. But even if it is there (on my machine) it still fails. Currently the branch fail on my pc, i'm in the process of fixing the travis build.

**Comment by yvoyer** [comment]
The last objective that fails is the assert that the method returns true, in fact it returns false. This is what's bugging me.

Any suggestions to make it work is welcome.

**Comment by yvoyer** [comment]
I'll merge this pr for now, and the other issues will be fixed on others pr.

**Pull request merged**
